### ISSUE TITLE
Wrong package name in the installation guide

### ISSUE THREAD

**Issue by SherkeyXD** [BEISNWKZNAN/nonebot-plugin-essence-message#1]
https://github.com/BEISNWKZNAN/nonebot-plugin-essence-message/blob/f47fe304113f1fb726f61fcbf5cb41750e62e8c6/README.md?plain=1#L31-L37

`nonebot-plugin-essence-message` should be `nonebot_plugin_essence_message`

**Comment by MovFish** [comment]
Thank you for the report! The pull request has been merged.
