### ISSUE TITLE
[Bug] 发送消息目标混乱

### ISSUE THREAD

**Issue by SherkeyXD** [BEISNWKZNAN/nonebot-plugin-essence-message#12]
常常会出现在一个群调用功能后，消息发往另一个群的情况
Related to #8，但不仅限于 `fetchall`，`help` 也有相同情况
![974d4d6b04401afd121e4a16d2e4947a](https://github.com/user-attachments/assets/f43e8131-9c3e-4fec-9402-622d5d372350)

**Comment by SherkeyXD** [comment]
初步 debug 判断为 alconna 解析后的 event 返回了错误的群 id

**Comment by SherkeyXD** [comment]
怀疑为 alconna 的 dispatch 问题
将所有 dispatch 换成 assign 并且去除权限控制之后没有出现错群的情况

**Comment by MovFish** [comment]
> 怀疑为 alconna 的 dispatch 问题 将所有 dispatch 换成 assign 并且去除权限控制之后没有出现错群的情况

改了
