### ISSUE TITLE
[Bug] `essence saveall` 获取图片错误

### ISSUE THREAD

**Issue by SherkeyXD** [BEISNWKZNAN/nonebot-plugin-essence-message#13]
获取 `sender_time` 错误
![image](https://github.com/user-attachments/assets/45e5d984-4ce2-4e7b-9e16-c718ea04246e)

**Comment by MovFish** [comment]
改为了operator_time,因为fetchall调用get_essence_msg_list使用了operator_time,所以应该可以默认使用的框架有operator_time
