### ISSUE TITLE
[Bug] 群员昵称显示不正常

### ISSUE THREAD

**Issue by 050644zf** [BEISNWKZNAN/nonebot-plugin-essence-message#9]
如图所示

![image](https://github.com/user-attachments/assets/fcde4b8e-dfa5-4cea-984d-057c710c419d)

![image](https://github.com/user-attachments/assets/6b91c1cc-9815-4418-a3e4-71f33feee800)

**Comment by MovFish** [comment]
已更新关于群昵称为空的判断

**Comment by 050644zf** [comment]
![Screenshot_2024-08-30-14-11-47-816_com.tencent.mobileqq.png](https://github.com/user-attachments/assets/61a78976-d4d6-4168-8a46-effadd92e36b)

0.2.4还是不行，尝试fetchall以及重新安装插件再fetchall还是不显示
